### ISSUE TITLE
The base image contains an unspecified and out of date version of V

### ISSUE THREAD

**Issue by hraftery** [exercism/vlang-test-runner#10]
The `thevlang/vlang` base image does not have tags that specify the version of V used, meaning that each time it runs it's possible a different version of V is used to run the tests. V is in early development and significant changes are common.

Currently the base image contains `V 0.3.2 0146509`, which is 2.5 months old. It fails to run the test suite for [simple-linked-list](https://exercism.org/tracks/vlang/exercises/simple-linked-list) with messages like "run_test.v:40:7: error: pop() returns an option, so it should have either an `or {}` block, or `?` at the end". Newer versions, such as used by the `configlet` test in the `exercism/vlang` repo itself, run the tests just fine.

Perhaps it makes sense for both `exercism/vlang` and `exercism/vlang-test-runner` to manually pin to the same recent build of V (say, by pulling a specific commit from the source repo and building it), at least until stable releases are available from the V project?

**Comment by ErikSchierboom** [comment]
> Perhaps it makes sense for both exercism/vlang and exercism/vlang-test-runner to manually pin to the same recent build of V (say, by pulling a specific commit from the source repo and building it), at least until stable releases are available from the V project?

We could do that for the test runner, but it would be less easy for the track itself. I think we should probably regularly rebuild the container. I'm working on that here: https://github.com/exercism/vlang-test-runner/pull/11

**Comment by hraftery** [comment]
Is it looking promising? I was under the impression the version of V is baked into the base image, so rebuilding the test-runner image won't help. But I don't think I have my head around it fully.

FWIW, the official install method for V is to pull the repo and build it. And now that I check, the track [seems to](https://github.com/exercism/vlang#setting-up-v) expect the user to do that as a prerequisite.

**Comment by ErikSchierboom** [comment]
It isn't really working no. Do you have time to look into this?

**Comment by hraftery** [comment]
Yeah sure, I can have a crack, as long as I keep the effort bounded. But I'm missing a lot of the overall Exercism design knowledge. My solution is likely to be a bit narrow minded. But if that's a step towards a better solution, then great.

**Comment by hraftery** [comment]
I've created the outline of the solution I had in mind. Miraculously, GitHub has found it and referenced it above.

To be sure, here it is: https://github.com/exercism/vlang-test-runner/compare/main...hraftery:exercism_vlang-test-runner:specify-v-version

I'm out for the day and will tidy this up another time. In the meantime, comments on this approach are most welcome.

**Comment by hraftery** [comment]
I tidied it up, satisfied myself that it was working well, and created a PR: https://github.com/exercism/vlang-test-runner/pull/12
